Repository spacetelescope/jwql, pull requests merged in 2018-11, with the labels that each got.

#162 Development Web Server Updates
  jwql/environment.yml
  jwql/website/jwql_proj/settings.py
  jwql/website/jwql_proj/urls.py
  jwql/website/jwql_proj/wsgi.py
Labels: Environment, Medium Priority, Web Application

#173 Remove "Quicklook" reference from outward-facing content
  README.md
  jwql/website/apps/jwql/templates/about.html
  jwql/website/apps/jwql/templates/archive.html
  jwql/website/apps/jwql/templates/base.html
  jwql/website/apps/jwql/templates/dashboard.html
  jwql/website/apps/jwql/templates/home.html
  jwql/website/apps/jwql/templates/instrument.html
  jwql/website/apps/jwql/templates/thumbnails.html
  jwql/website/apps/jwql/templates/view_header.html
  jwql/website/apps/jwql/templates/view_image.html
  jwql/website/apps/jwql/views.py
  jwql/website/jwql_proj/urls.py
Labels: Code Base, Documentation, Low Priority

#179 WIP: Add documentation button to top of base.html
  jwql/website/apps/jwql/templates/about.html
  jwql/website/apps/jwql/templates/base.html
Labels: Documentation, Low Priority, Web Application, enhancement

#192 Use requirements.txt for pyup and readthedocs configuration
  .pyup-requirements.txt
  .pyup.yml
  .readthedocs.yml
  requirements.txt
Labels: Environment, Low Priority

#185 Update django to avoid security vulnerability reported by GitHub
  environment.yml
  requirements.txt
Labels: High Priority, Web Application, bug

#194 API Documentation Updates
  README.md
  docs/source/database.rst
  docs/source/index.rst
  docs/source/jwql_monitors.rst
  docs/source/tests.rst
  docs/source/utils.rst
  environment.yml
  jwql/database/database_interface.py
  jwql/jwql_monitors/generate_preview_images.py
  jwql/jwql_monitors/monitor_filesystem.py
  jwql/utils/monitor_template.py
  jwql/utils/preview_image.py
  requirements.txt
Labels: Documentation, Low Priority, bug, enhancement

#169 Add web app API docs to sphinx
  docs/_config.yml
  docs/source/conf.py
  docs/source/index.rst
  docs/source/website.rst
  environment.yml
  jwql/website/apps/jwql/views.py
  jwql/website/manage.py
Labels: Documentation, Low Priority, Web Application, enhancement

#167 Simplified algorithm for determining if a log should be written to dev or not
  jwql/utils/logging_functions.py
Labels: Code Base, Low Priority, enhancement

#188 [WIP] No donut
  jwql/jwql_monitors/monitor_mast.py
  jwql/tests/test_plotting.py
  jwql/utils/plotting.py
Labels: Filesystem, Testing, bug
