Repository spacetelescope/jwql, pull requests merged in 2019-05, with the labels that each got.

#387 Updated jenkins file with new build matrix
  Jenkinsfile
  MANIFEST.in
  README.md
  environment_python_3_5.yml
  environment_python_3_6.yml
Labels: Environment, Testing

#404 Explicitly request use of conda in Jenkinsfile
  Jenkinsfile
  environment_python_3_5.yml
  environment_python_3_6.yml
Labels: Medium Priority, Testing, bug

#413 Relax requirements for gaussian 1d test
  jwql/tests/test_calculations.py
Labels: High Priority, Testing, bug

#414 Fix test_get_pipeline_steps for python 3.5
  jwql/tests/test_pipeline_tools.py
Labels: Low Priority, Testing, bug

#378 Put variables in constants.py in alphabetical order
  jwql/utils/constants.py
  jwql/utils/instrument_properties.py
Labels: Low Priority, Package, enhancement

#410 Edb access via web app login
  jwql/edb/engineering_database.py
  jwql/website/apps/jwql/data_containers.py
  jwql/website/apps/jwql/oauth.py
  jwql/website/apps/jwql/templates/engineering_database.html
  jwql/website/apps/jwql/views.py
Labels: Low Priority, Monitor, Web Application, enhancement

#412 Add sed command to remove invalid attrs from junit xml
  Jenkinsfile
Labels: Medium Priority, Testing, bug

#416 Fix test_completed_pipeline_steps for python 3.5
  jwql/tests/test_pipeline_tools.py
Labels: Low Priority, Testing, bug

#417 Fix web app redirect issues
  jwql/website/apps/jwql/oauth.py
Labels: Medium Priority, Web Application, bug

#421 Rename style_guide.md to README.md
  .pep8speaks.yml
  README.md
  jwql/utils/monitor_template.py
  style_guide/README.md
Labels: Documentation, Low Priority, enhancement

#397 Skip tests
  jwql/tests/test_api_views.py
  jwql/tests/test_edb.py
  jwql/tests/test_loading_times.py
  jwql/tests/test_logging_functions.py
  jwql/tests/test_permissions.py
  jwql/tests/test_pipeline_tools.py
  jwql/tests/test_utils.py
Labels: Low Priority, Testing

#415 Add download buttons to EDB page
  .gitignore
  jwql/website/apps/jwql/data_containers.py
  jwql/website/apps/jwql/templates/engineering_database.html
  jwql/website/apps/jwql/views.py
Labels: Low Priority, Web Application

#420 Leading zeros not required for proposal number
  jwql/tests/test_api_views.py
  jwql/website/apps/jwql/data_containers.py
  jwql/website/apps/jwql/forms.py
  jwql/website/apps/jwql/static/js/jwql.js
  jwql/website/apps/jwql/templates/home.html
  jwql/website/apps/jwql/urls.py
Labels: Low Priority, Web Application, enhancement

#422 Smarter handling of auth errors
  jwql/edb/engineering_database.py
  jwql/utils/credentials.py
  jwql/utils/utils.py
  jwql/website/apps/jwql/data_containers.py
  jwql/website/apps/jwql/forms.py
  jwql/website/apps/jwql/oauth.py
Labels: Documentation, Low Priority, Web Application
