Repository spacetelescope/jwql, pull requests merged in 2019-03, with the labels that each got.

#314 Fix instrument logos on homepage
  jwql/website/apps/jwql/static/img/fgslogo.png
  jwql/website/apps/jwql/static/img/mirilogo.png
  jwql/website/apps/jwql/static/img/nircamlogo.png
  jwql/website/apps/jwql/static/img/nirisslogo.png
  jwql/website/apps/jwql/static/img/nirspeclogo.png
Labels: Low Priority, Web Application, bug

#313 Update API docs
  docs/source/edb.rst
  docs/source/index.rst
  docs/source/tests.rst
  docs/source/utils.rst
  docs/source/website.rst
  jwql/__init__.py
  jwql/database/database_interface.py
Labels: Documentation, Low Priority, enhancement

#315 Fix filename parser for new filenames
  jwql/tests/test_utils.py
  jwql/utils/constants.py
  jwql/utils/utils.py
Labels: Filesystem, Medium Priority, Package

#316 Update docs for JS functions in web app
  jwql/website/apps/jwql/static/js/jwql.js
  jwql/website/apps/jwql/templates/view_image.html
Labels: Documentation, Low Priority, Web Application, enhancement

#319 Fix static references and move lingering JS functions from HTML templates to jwql.js
  jwql/website/apps/jwql/static/js/jwql.js
  jwql/website/apps/jwql/templates/archive.html
  jwql/website/apps/jwql/templates/instrument.html
  jwql/website/apps/jwql/templates/thumbnails.html
  jwql/website/apps/jwql/templates/view_image.html
Labels: Low Priority, Web Application, bug

#317 Pass base context through context processor
  docs/source/website.rst
  jwql/website/apps/jwql/context_processors.py
  jwql/website/apps/jwql/views.py
  jwql/website/jwql_proj/settings.py
Labels: Medium Priority, Web Application, enhancement

#321 Reset database
  docs/source/database.rst
  jwql/database/database_interface.py
  jwql/database/reset_database.py
Labels: Database, Low Priority, enhancement

#323 Always output instrument from filename_parser
  jwql/tests/test_utils.py
  jwql/utils/utils.py
  jwql/website/apps/jwql/forms.py
Labels: Web Application, bug

#331 Add FileNotFoundError to "raises" for filename_parser test
  jwql/tests/test_utils.py
Labels: Medium Priority, Testing, bug

#332 Release 0.18.0
  CHANGES.rst
  setup.py
Labels: Documentation, Medium Priority, Package

#337 Release 0.18.0
  CHANGES.rst
  setup.py
Labels: Documentation, Medium Priority, Package

#333 Release-driven git workflow
  README.md
  style_guide/style_guide.md
Labels: Documentation, Medium Priority

#203 initial commit of Jenkins RT file
  JenkinsfileRT
Labels: Medium Priority, Testing, enhancement

#328 Update monitor_filesystem to use database tables
  jwql/database/database_interface.py
  jwql/jwql_monitors/monitor_filesystem.py
Labels: Database, Medium Priority, Monitor, enhancement

#206 Implement code-cov
  Jenkinsfile
  codecov.yml
  environment.yml
  requirements.txt
Labels: Low Priority, Testing, enhancement
