Repository spacetelescope/jwql, pull requests merged in 2019-06, with the labels that each got.

#427 Anomaly submission form
  environment_python_3_5.yml
  environment_python_3_6.yml
  jwql/database/database_interface.py
  jwql/jwql_monitors/generate_preview_images.py
  jwql/tests/test_database_interface.py
  jwql/utils/constants.py
  jwql/utils/preview_image.py
  jwql/website/apps/jwql/data_containers.py
  jwql/website/apps/jwql/forms.py
  jwql/website/apps/jwql/static/css/jwql.css
  jwql/website/apps/jwql/templates/view_image.html
  jwql/website/apps/jwql/views.py
  requirements.txt
Labels: Medium Priority, Web Application, enhancement

#430 Release 0.20.0 [develop]
  CHANGES.rst
  setup.py
Labels: Documentation, Medium Priority, Package

#419 Upload JWQL to PyPI
  Jenkinsfile
  environment_python_3_5.yml
  environment_python_3_6.yml
  setup.py
Labels: Medium Priority, Package

#429 Update web app bokeh version
  jwql/website/apps/jwql/templates/base.html
Labels: Environment, Medium Priority, Web Application, bug

#432 Add bokeh version test
  jwql/tests/test_plotting.py
Labels: Low Priority, Testing, Web Application

#440 Improve test_database_interface
  jwql/tests/test_database_interface.py
Labels: Low Priority, Testing, enhancement

#444 Fix test_api_views for miri thumbnails
  jwql/tests/test_api_views.py
  jwql/tests/test_plotting.py
  jwql/website/apps/jwql/templates/dashboard.html
  jwql/website/apps/jwql/templates/engineering_database.html
  jwql/website/apps/jwql/templates/filesystem_monitor_full.html
  jwql/website/apps/jwql/templates/miri_data_trending.html
  jwql/website/apps/jwql/templates/nirspec_data_trending.html
Labels: Testing, bug

#447 Increase width of footer object containing jwql version number
  jwql/website/apps/jwql/static/css/jwql.css
Labels: Low Priority, Web Application, bug

#448 Update web app to use django 2.2
  environment_python_3_6.yml
  jwql/website/apps/jwql/views.py
  jwql/website/jwql_proj/settings.py
Labels: Environment, Medium Priority, Web Application, enhancement

#453 Fix guass_peak typo in column names
  jwql/database/monitor_table_definitions/fgs/fgs_dark_dark_current.txt
  jwql/database/monitor_table_definitions/miri/miri_dark_dark_current.txt
  jwql/database/monitor_table_definitions/nircam/nircam_dark_dark_current.txt
  jwql/database/monitor_table_definitions/niriss/niriss_dark_dark_current.txt
  jwql/database/monitor_table_definitions/nirspec/nirspec_dark_dark_current.txt
Labels: Database, Low Priority, bug

#450 Updated README to include pip install instructions
  README.md
Labels: Documentation, Low Priority, Package, enhancement
