Repository spacetelescope/jwql, pull requests merged in 2020-11, with the labels that each got.

#655 Fix test_data_containers
  environment_python_3_6.yml
  environment_python_3_7.yml
  environment_python_3_8.yml
  jwql/tests/test_data_containers.py
  jwql/website/apps/jwql/data_containers.py
  requirements.txt
  setup.py
Labels: Testing, bug

#654 Fix test_utils
  jwql/utils/utils.py
Labels: Testing, bug

#662 Switch EDB MAST token authentication to use config.json
  jwql/utils/credentials.py
Labels: bug

#663 Make JWQL citable
  README.md
Labels: Documentation

#659 Reorganize Instrument Landing Page
  jwql/website/apps/jwql/templates/instrument.html
Labels: Web Application
