Repository spacetelescope/jwql, pull requests merged in 2020-04, with the labels that each got.

#564 Expand database_interface to support instrument-specific anomalies
  jwql/database/database_interface.py
  jwql/tests/test_database_interface.py
  jwql/utils/constants.py
  jwql/website/apps/jwql/data_containers.py
  jwql/website/apps/jwql/views.py
  jwql/website/db.sqlite3
Labels: High Priority, Monitor

#567 #497 pep8speaks - Disable E501 Line Too Long error
  .pep8speaks.yml
Labels: Low Priority, Package

#568 MIRI and NIRSpec Anomalies
  jwql/utils/constants.py
Labels: Database, Low Priority
