Repository spacetelescope/jwql, pull requests merged in 2021-06, with the labels that each got.

#724 Config file handling
  .gitignore
  README.md
  example_config.json
  jwql/__init__.py
  jwql/database/database_interface.py
  jwql/jwql_monitors/monitor_cron_jobs.py
  jwql/jwql_monitors/monitor_filesystem.py
  jwql/tests/test_utils.py
  jwql/utils/logging_functions.py
  jwql/utils/monitor_template.py
  jwql/utils/utils.py
  jwql/website/apps/jwql/bokeh_dashboard.py
  jwql/website/apps/jwql/forms.py
  jwql/website/apps/jwql/monitor_views.py
  jwql/website/apps/jwql/oauth.py
  jwql/website/apps/jwql/views.py
  notebooks/edb_mnemonic_query.ipynb
Labels: Package, enhancement

#745 Fix RTD build failures
  MANIFEST.in
  docs/source/conf.py
  docs/source/tests.rst
  jwql/bokeh_templating/factory.py
  jwql/bokeh_templating/template.py
  jwql/example_config.json
  jwql/instrument_monitors/miri_monitors/data_trending/utils/__init__.py
  jwql/tests/test_preview_image.py
  jwql/utils/instrument_properties.py
  jwql/utils/monitor_template.py
  jwql/utils/utils.py
  jwql/website/apps/jwql/api_views.py
  jwql/website/apps/jwql/data_containers.py
  jwql/website/apps/jwql/oauth.py
  rtd_requirements.txt
  setup.py
Labels: Documentation

#726 Switch filesystem to MAST isilon storage
  jwql/jwql_monitors/generate_preview_images.py
  jwql/jwql_monitors/monitor_filesystem.py
  jwql/tests/test_data_containers.py
  jwql/tests/test_pipeline_tools.py
  jwql/tests/test_utils.py
  jwql/utils/monitor_template.py
  jwql/utils/organize_filesystem.py
  jwql/utils/preview_image.py
  jwql/utils/utils.py
  jwql/website/apps/jwql/data_containers.py
  jwql/website/apps/jwql/forms.py
  jwql/website/apps/jwql/views.py
Labels: Filesystem
