Repository spacetelescope/jwql, pull requests merged in 2021-05, with the labels that each got.

#732 Update pysiaf
  environment_python_3_8.yml
  requirements.txt
Labels: dependencies

#723 Provide an easy way for users to submit bugs and feature requests
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  jwql/website/apps/jwql/templates/about.html
Labels: Documentation, enhancement

#712 Adding Bandit Security Check to Github Actions
  .github/workflows/ci.yml
Labels: Package, Testing
