Repository spacetelescope/jwql, pull requests merged in 2021-02, with the labels that each got.

#696 Fix filename parsing for WFS&C and AMI products
  jwql/utils/constants.py
Labels: Filesystem

#697 Remove Python 3.6 Support
  Jenkinsfile
  README.md
  environment_python_3_6.yml
Labels: Environment

#701 Updating yaml environment file names
  README.md
Labels: Documentation
