Repository spacetelescope/jwql, pull requests merged in 2021-12, with the labels that each got.

#828 Update EDB
  environment_python_3_7.yml
  environment_python_3_8.yml
  jwql/edb/engineering_database.py
  jwql/example_config.json
  jwql/utils/credentials.py
  jwql/website/apps/jwql/data_containers.py
  jwql/website/apps/jwql/forms.py
  jwql/website/apps/jwql/templates/engineering_database.html
  requirements.txt
Labels: bug, enhancement, Web Application

#836 Made plotting limits robust to missing data
  jwql/website/apps/jwql/monitor_pages/monitor_bias_bokeh.py
  jwql/website/apps/jwql/monitor_pages/monitor_readnoise_bokeh.py
Labels: bug

#841 Switch to test string for astroquery.mast queries
  jwql/edb/engineering_database.py
  jwql/example_config.json
  jwql/jwql_monitors/monitor_mast.py
  jwql/tests/test_dark_monitor.py
  jwql/tests/test_monitor_mast.py
  jwql/website/apps/jwql/data_containers.py
Labels: bug, Filesystem

#838 Updating Bandit CI
  .bandit
  .github/workflows/ci.yml
  environment_python_3_7.yml
  environment_python_3_8.yml
  jwql/bokeh_templating/template.py
  jwql/tests/test_bias_monitor.py
  jwql/utils/logging_functions.py
  jwql/website/apps/jwql/data_containers.py
  jwql/website/jwql_proj/jinja2.py
  jwql/website/jwql_proj/settings.py
  requirements.txt
  rtd_requirements.txt
  setup.py
Labels: enhancement, Testing

#829 Cross-origin request fix
  jwql/utils/utils.py
  jwql/website/apps/jwql/views.py
  rtd_requirements.txt
Labels: bug

#843 Import initialize_instrument_monitor from the correct location
  jwql/jwql_monitors/generate_preview_images.py
  rtd_requirements.txt
Labels: bug

#844 Fix archive webpage ajax issue
  jwql/utils/constants.py
  jwql/website/apps/jwql/views.py
Labels: bug, Web Application
